### PR TITLE
Update Document.php

### PR DESCRIPTION
**Pull request by SeppeMagiels**
Laravie\Parser changed the signature. Now they don't match and you get an error.

### CODE REVIEW

**Comment by crynobone** [comment]
Test still runs fine.

**Comment by SeppeMagiels** [comment]
With the version composer is downloading (^2.1.2) it doesn't... I always get the same php error: 
 Declaration of Orchestra\Parser\Xml\Document::callFilterResolver(callable $resolver, $value) should be compatible with Laravie\Parser\Document::callFilterResolver($resolver, $value)
 
Seems to happen to all my new installs, I assume composer is getting the wrong version of Laravie\Parser then...

**Comment by crynobone** [comment]
> Declaration of Orchestra\Parser\Xml\Document::callFilterResolver(callable $resolver, $value) should be compatible with Laravie\Parser\Document::callFilterResolver($resolver, $value)

Create failing tests for this first.

**Comment by crynobone** [comment]
Released 2.1.5

**Pull request closed without merging**
